local colors = {}

if vim.g.MdsCompat then
  colors = require("midnightseadragon.colors").compat256
else
  colors = require("midnightseadragon.colors").default
end

local M = {}

M.default = {
    Normal = { fg = colors.fg0, bg = colors.bg0 },
    StatusLine = { fg = colors.seafoam_l, bg = colors.bg2 },
    StatusLineNC = { fg = colors.fg3, bg = colors.bg1 },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { bg = colors.bg1 },
    MatchParen = { fg = colors.yellow_l },
    ColorColumn = { bg = colors.bg3 },
    Conceal = { fg = colors.bg2 },
    NonText = { fg = colors.bg2 },
    SpecialKey = { fg = colors.bg2 },
    Visual = { bg = colors.bg4 },
    VisualNOS = { bg = colors.fg4 },
    Search = { fg = colors.yellow_l, bg = colors.black_l },
    IncSearch = {  fg = colors.black_d, bg = colors.ice_d },
    CurSearch = { fg = colors.black_d, bg = colors.ice_d },
    VertSplit = { fg = colors.bg2, bg = colors.bg0 },
    Directory = { fg = colors.blue_d },
    Title = { fg = colors.seafoam_l },
    ErrorMsg = { fg = colors.red_l, bg = colors.bg0, bold = true },
    MoreMsg = { fg = colors.dcyan },
    ModeMsg = { fg = colors.white_d, bold = true, reverse = true },
    Question = { fg = colors.magenta_l, bold = true },
    WarningMsg = { fg = colors.bg1, bg = colors.yellow_l, bold = true, italic = true },
    EndOfBuffer = { fg = colors.fg4, bg = colors.bg0 },
    Pmenu = { fg = colors.fg3, bg = colors.bg1 },
    PmenuSel = { fg = colors.cyan_l, bg = colors.bg2 },
    PmenuSbar = { fg = colors.fg4, bg = colors.bg3 },
    PmenuThumb = { fg = colors.seafoam_d, bg = colors.fg4 },
    CursorLineNr = { fg = colors.seafoam_l },
    LineNr = { fg = colors.cyan_d },
    Folded = { fg = colors.fg4, bg = colors.bg1, bold = true, italic = true },
    FoldColumn = { fg = colors.fg4, bg = colors.bg1, bold = true, italic = true },
    SignColumn = { fg = colors.fg4, bg = colors.bg1, bold = true, italic = true },
    DiagnosticWarn = { fg = colors.orange_l },
    DiagnosticError = { fg = colors.red_l },
    DiagnosticInfo = { fg = colors.cyan_l },
    DiagnosticHint = { fg = colors.fg1 },
    DiagnosticUnderlineWarn = { sp = colors.orange_l, undercurl = true },
    DiagnosticUnderlineError = { sp = colors.red_l, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.cyan_l, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.fg1, underline = true },

    -- Syntax highlighting
    Comment = {fg = colors.fg4 },
    Constant = {fg = colors.green_l },
    String = {fg = colors.green_l },
    Character = {fg = colors.green_d },
    Number = {fg = colors.yellow_d },
    Float = {fg = colors.yellow_d },
    Boolean = {fg = colors.yellow_d },
    Identifier = {fg = colors.cyan_l },
    Function = {fg = colors.seafoam_l },
    Statement = {fg = colors.orange_l },
    Conditional = {fg = colors.red_l },
    Repeat = {fg = colors.red_l },
    Label = { fg = colors.orange_d },
    Operator = { fg = colors.white_d },
    Keyword = { fg = colors.orange_l },
    Exception = { fg = colors.red_l },
    PreProc = { fg = colors.blue_d },
    Include = { fg = colors.blue_d },
    Define = { fg = colors.blue_d },
    Macro = { fg = colors.blue_d },
    PreCondit = { fg = colors.magenta_d },
    Type = { fg = colors.magenta_l },
    StorageClass = { fg = colors.yellow_d },
    Structure = { fg = colors.cyan_d },
    Typedef = { fg = colors.magenta_d },
    Special = { fg = colors.yellow_l },
    SpecialChar = { fg = colors.yellow_l },
    Tag = { fg = colors.seafoam_d },
    Delimiter = { fg = colors.white_d },
    SpecialComment = { fg = colors.bg4 },
    Debug = { fg = colors.white_l },
    Underlined = { fg = colors.seafoam_l, underline = true },
    Error = { fg = colors.red_d, bold = true },
    Todo = { fg = colors.yellow_l, bold = true },

    ["@variable"] = { fg = colors.cyan_l },
    ["@variable.builtin"] = { fg = colors.cyan_d },
    ["@variable.parameter"] = { fg = colors.cyan_d },
    ["@variable.parameter.builtin"] = { fg = colors.magenta_l },
    ["@variable.member"] = { fg = colors.cyan_l },

    ["@constant"] = { fg = colors.blue_d },
    ["@constant.builtin"] = { fg = colors.magenta_d },
    ["@constant.macro"] = { fg = colors.blue_d },

    ["@module"] = { fg = colors.seafoam_d },
    ["@module.builtin"] = { fg = colors.seafoam_d },
    ["@label"] = { fg = colors.blue_d },

    ["@string"] = { fg = colors.green_l },
    ["@string.documentation"] = { fg = colors.green_d },
    ["@string.regexp"] = { fg = colors.yellow_l },
    ["@string.escape"] = { fg = colors.yellow_l },
    ["@string.special"] = { fg = colors.yellow_l },
    ["@string.special.symbol"] = { fg = colors.seafoam_l },
    ["@string.special.path"] = { fg = colors.green_d },
    ["@string.special.url"] = { fg = colors.seafoam_l },

    ["@character"] = { fg = colors.green_d },
    ["@character.special"] = { fg = colors.seafoam_l },

    ["@boolean"] = { fg = colors.yellow_d },
    ["@number"] = { fg = colors.yellow_d },
    ["@number.float"] = { fg = colors.yellow_d },

    ["@type"] = { fg = colors.magenta_d },
    ["@type.builtin"] = { fg = colors.magenta_l },
    ["@type.definition"] = { fg = colors.blue_l },

    ["@attribute"] = { fg = colors.yellow_d },
    ["@attribute.builtin"] = { fg = colors.yellow_l },
    ["@property"] = { fg = colors.blue_l },

    ["@function"] = { fg = colors.seafoam_l },
    ["@function.builtin"] = { fg = colors.orange_l },
    ["@function.call"] = { fg = colors.seafoam_l },
    ["@function.macro"] = { fg = colors.seafoam_d },

    ["@function.method"] = { fg = colors.seafoam_l },
    ["@function.method.call"] = { fg = colors.seafoam_l },

    ["@constructor"] = { fg = colors.magenta_l },
    ["@operator"] = { fg = colors.white_d },

    ["@keyword"] = { fg = colors.orange_l },
    ["@keyword.coroutine"] = { fg = colors.orange_d },
    ["@keyword.function"] = { fg = colors.orange_l },
    ["@keyword.operator"] = { fg = colors.orange_d },
    ["@keyword.import"] = { fg = colors.blue_d },
    ["@keyword.type"] = { fg = colors.orange_l },
    ["@keyword.modifier"] = { fg = colors.yellow_d },
    ["@keyword.repeat"] = { fg = colors.red_d },
    ["@keyword.return"] = { fg = colors.red_l },
    ["@keyword.debug"] = { fg = colors.red_l },
    ["@keyword.exception"] = { fg = colors.red_l },

    ["@keyword.conditional"] = { fg = colors.red_d },
    ["@keyword.conditional.ternary"] = { fg = colors.red_d },

    ["@keyword.directive"] = { fg = colors.magenta_d },
    ["@keyword.directive.define"] = { fg = colors.blue_d },

    ["@punctuation.delimiter"] = { fg = colors.white_d },
    ["@punctuation.bracket"] = { fg = colors.white_l },
    ["@punctuation.special"] = { fg = colors.yellow_l },

    ["@comment"] = { fg = colors.fg4 },
    ["@comment.documentation"] = { fg = colors.white_d },

    ["@comment.error"] = { fg = colors.red_l },
    ["@comment.warning"] = { fg = colors.orange_l },
    ["@comment.todo"] = { fg = colors.yellow_l },
    ["@comment.note"] = { fg = colors.white_d },

    ["@markup.strong"] = { fg = colors.blue_l, bold = true },
    ["@markup.italic"] = { fg = colors.green_l, italic = true },
    ["@markup.strikethrough"] = { fg = colors.white_d, strikethrough = true },
    ["@markup.underline"] = { underline = true },

    ["@markup.heading"] = { fg = colors.magenta_l, bold = true },
    ["@markup.heading.1"] = { fg = colors.red_l, bold = true },
    ["@markup.heading.2"] = { fg = colors.orange_l, bold = true },
    ["@markup.heading.3"] = { fg = colors.yellow_l, bold = true },
    ["@markup.heading.4"] = { fg = colors.green_l, bold = true },
    ["@markup.heading.5"] = { fg = colors.blue_l, bold = true },
    ["@markup.heading.6"] = { fg = colors.magenta_l, bold = true },

    ["@markup.quote"] = { fg = colors.seafoam_d },
    ["@markup.math"] = { fg = colors.seafoam_d },

    ["@markup.link"] = { fg = colors.blue_d },
    ["@markup.link.label"] = { fg = colors.cyan_l },
    ["@markup.link.url"] = { fg = colors.seafoam_l },

    -- Language Specific
    rustDerive = { fg = colors.magenta_l },
    rustSigil = { fg = colors.orange_l },
    rustQuestionMark = { fg = colors.orange_l },
    rustAttribute = { fg = colors.blue_d },
    rustStructure = { fg = colors.orange_d },
    rustStorage = { fg = colors.magenta_d },
    rustFuncCall = { fg = colors.seafoam_l },
    rustIdentifier = { fg = colors.cyan_l },
    rustType = { fg = colors.seafoam_l },
    rustTrait = { fg = colors.magenta_l },
    rustOperator = { fg = colors.white_d },
}

return M
